[build]
  command = "npm run build"  # Adjust this command based on your project setup
  publish = "frontend/build"  # Adjust the publish directory based on your project structure

[[redirects]]
  from = "/api/*"
  to = "https://www.litlepawsdr.org/api/:splat"
  status = 200
