[build]
  base = "web"
  command = "npm run build"  # Adjust this command based on your project setup
  publish = "build"  # Adjust the publish directory based on your project structure

[[redirects]]
  from = "/api/*"
  to = "https://littlepawsdr.herokuapp.com/api/:splat"
  status = 200
