export const ACTION_HISTORY_LIST_REQUEST = 'ACTION_HISTORY_LIST_REQUEST';
export const ACTION_HISTORY_LIST_SUCCESS = 'ACTION_HISTORY_LIST_SUCCESS';
export const ACTION_HISTORY_LIST_FAIL = 'ACTION_HISTORY_LIST_FAIL';
export const ACTION_HISTORY_LIST_RESET = 'ACTION_HISTORY_LIST_RESET';
