export const ADOPTION_FEE_REQUEST = 'ADOPTION_FEE_REQUEST';
export const ADOPTION_FEE_SUCCESS = 'ADOPTION_FEE_SUCCESS';
export const ADOPTION_FEE_FAIL = 'ADOPTION_FEE_FAIL';
export const ADOPTION_FEE_RESET = 'ADOPTION_FEE_RESET';

export const ADOPTION_FEE_ACTIVE_SESSION_REQUEST =
  'ADOPTION_FEE_ACTIVE_SESSION_REQUEST';
export const ADOPTION_FEE_ACTIVE_SESSION_SUCCESS =
  'ADOPTION_FEE_ACTIVE_SESSION_SUCCESS';
export const ADOPTION_FEE_ACTIVE_SESSION_FAIL =
  'ADOPTION_FEE_ACTIVE_SESSION_FAIL';
export const ADOPTION_FEE_ACTIVE_SESSION_RESET =
  'ADOPTION_FEE_ACTIVE_SESSION_RESET';

export const ADOPTION_FEE_LIST_REQUEST = 'ADOPTION_FEE_LIST_REQUEST';
export const ADOPTION_FEE_LIST_SUCCESS = 'ADOPTION_FEE_LIST_SUCCESS';
export const ADOPTION_FEE_LIST_FAIL = 'ADOPTION_FEE_LIST_FAIL';
export const ADOPTION_FEE_LIST_RESET = 'ADOPTION_FEE_LIST_RESET';
