export const ARCHIVE_ANNUAL_DATA_REQUEST = 'ARCHIVE_ANNUAL_DATA_REQUEST';
export const ARCHIVE_ANNUAL_DATA_SUCCESS = 'ARCHIVE_ANNUAL_DATA_SUCCESS';
export const ARCHIVE_ANNUAL_DATA_FAIL = 'ARCHIVE_ANNUAL_DATA_FAIL';
export const ARCHIVE_ANNUAL_DATA_RESET = 'ARCHIVE_ANNUAL_DATA_RESET';
