export const CART_ADD_ITEM_REQUEST = 'CARD_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM = 'CARD_ADD_ITEM';
export const CART_ADD_ITEM_FAIL = 'CARD_ADD_ITEM_FAIL';
export const CART_ADD_ITEM_FAIL_RESET = 'CART_ADD_ITEM_FAIL_RESET';
export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_ADD_ITEM_RESET = 'CART_ADD_ITEM_RESET';

export const WELCOME_WIENER_ADD_CART_ITEM_REQUEST =
  'WELCOME_WIENER_ADD_CART_ITEM_REQUEST';
export const WELCOME_WIENER_ADD_CART_ITEM_SUCCESS =
  'WELCOME_WIENER_ADD_CART_ITEM_SUCCESS';
export const WELCOME_WIENER_ADD_CART_ITEM_FAIL =
  'WELCOME_WIENER_ADD_CART_ITEM_FAIL';
export const WELCOME_WIENER_ADD_CART_ITEM_RESET =
  'WELCOME_WIENER_ADD_CART_ITEM_RESET';

export const WELCOME_WIENER_DELETE_CART_ITEM_SUCCESS =
  'WELCOME_WIENER_DELETE_CART_ITEM_SUCCESS';

export const WELCOME_WIENER_REMOVE_CART_ITEM =
  'WELCOME_WIENER_REMOVE_CART_ITEM';

export const OPEN_CART_DRAWER = 'OPEN_CART_DRAWER';
