export const CART_ADD_ITEM_REQUEST = 'CARD_ADD_ITEM_REQUEST';
export const CART_ADD_ITEM = 'CARD_ADD_ITEM';
export const CART_ADD_ITEM_FAIL = 'CARD_ADD_ITEM_FAIL';
export const CART_ADD_ITEM_FAIL_RESET = 'CART_ADD_ITEM_FAIL_RESET';
export const CART_CLEAR_ITEMS = 'CART_RESET';
export const CART_REMOVE_ITEM = 'CARD_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD';
