export const CART_ADD_ITEM_FAIL_RESET = 'CART_ADD_ITEM_FAIL_RESET';
export const CART_CLEAR_ITEMS = 'CART_RESET';

export const CART_ADD_ITEM_SUCCESS = 'CART_ADD_ITEM_SUCCESS';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const OPEN_CART_DRAWER = 'OPEN_CART_DRAWER';

export const CART_DELETE_ITEM_SUCCESS = 'CART_DELETE_ITEM_SUCCESS';
export const PRODUCT_ADD_CART_ITEM_FAIL = 'PRODUCT_ADD_CART_ITEM_FAIL';
export const PRODUCT_DELETE_FROM_CART_FAIL = 'PRODUCT_DELETE_FROM_CART_FAIL';
export const PRODUCT_REMOVE_FROM_CART_FAIL = 'PRODUCT_REMOVE_FROM_CART_FAIL';

export const UPDATE_CART = 'UPDATE_CART';
