export const DACHSHUND_REQUEST = 'DACHSHUND_REQUEST';
export const DACHSHUNDS_SUCCESS = 'DACHSHUNDS_SUCCESS';
export const DACHSHUNDS_FAIL = 'DACHSHUNDS_FAIL';

export const DACHSHUND_DETAILS_REQUEST = 'DACHSHUND_DETAILS_REQUEST';
export const DACHSHUND_DETAILS_SUCCESS = 'DACHSHUND_DETAILS_SUCCESS';
export const DACHSHUND_DETAILS_FAIL = 'DACHSHUND_DETAILS_FAIL';
export const DACHSHUND_DETAILS_RESET = 'DACHSHUND_DETAILS_RESET';

export const DACHSHUND_SUCCESSFUL_ADOPTIONS_REQUEST = 'DACHSHUND_SUCCESSFUL_ADOPTIONS_REQUEST';
export const DACHSHUND_SUCCESSFUL_ADOPTIONS_SUCCESS = 'DACHSHUND_SUCCESSFUL_ADOPTIONS_SUCCESS';
export const DACHSHUND_SUCCESSFUL_ADOPTIONS_FAIL = 'DACHSHUND_SUCCESSFUL_ADOPTIONS_FAIL';

export const DACHSHUND_SANCTUARY_OR_PASSED_AWAY_REQUEST = 'DACHSHUND_SANCTUARY_OR_PASSED_AWAY_REQUEST';
export const DACHSHUND_SANCTUARY_OR_PASSED_AWAY_SUCCESS = 'DACHSHUND_SANCTUARY_OR_PASSED_AWAY_SUCCESS';
export const DACHSHUND_SANCTUARY_OR_PASSED_AWAY_FAIL = 'DACHSHUND_SANCTUARY_OR_PASSED_AWAY_FAIL';

export const DACHSHUND_PICS_VIDS_STASTUSES_REQUEST = 'DACHSHUND_PICS_VIDS_STASTUSES_REQUEST';
export const DACHSHUND_PICS_VIDS_STASTUSES_SUCCESS = 'DACHSHUND_PICS_VIDS_STASTUSES_SUCCESS';
export const DACHSHUND_PICS_VIDS_STASTUSES_FAIL = 'DACHSHUND_PICS_VIDS_STASTUSES_FAIL';

export const TOTAL_DACHSHUND_COUNT_REQUEST = 'TOTAL_DACHSHUND_COUNT_REQUEST';
export const TOTAL_DACHSHUND_COUNT_SUCCESS = 'TOTAL_DACHSHUND_COUNT_SUCCESS';
export const TOTAL_DACHSHUND_COUNT_FAIL = 'TOTAL_DACHSHUND_COUNT_FAIL';
