export const OPEN_CLOSE_DASHBOARD_MODAL = 'OPEN_CLOSE_DASHBOARD_MODAL';

export const LINE_CHART_DATA = 'LINE_CHART_DATA';

export const DASHBOARD_CURRENT_YEAR_DATA_REQUEST =
  'DASHBOARD_CURRENT_YEAR_DATA_REQUEST';
export const DASHBOARD_CURRENT_YEAR_DATA_SUCCESS =
  'DASHBOARD_CURRENT_YEAR_DATA_SUCCESS';
export const DASHBOARD_CURRENT_YEAR_DATA_FAIL =
  'DASHBOARD_CURRENT_YEAR_DATA_FAIL';
