export const DONATE_CREATE_REQUEST = "DONATE_CREATE_REQUEST";
export const DONATE_CREATE_SUCCESS = "DONATE_CREATE_SUCCESS";
export const DONATE_CREATE_FAIL = "DONATE_CREATE_FAIL";
export const DONATE_CREATE_RESET = "DONATE_CREATE_RESET";

export const DONATE_DETAILS_REQUEST = "DONATE_DETAILS_REQUEST";
export const DONATE_DETAILS_SUCCESS = "DONATE_DETAILS_SUCCESS";
export const DONATE_DETAILS_FAIL = "DONATE_DETAILS_FAIL";
export const DONATE_DETAILS_RESET = 'DONATE_DETAILS_RESET';

export const DONATE_LIST_REQUEST = "DONATE_LIST_REQUEST";
export const DONATE_LIST_SUCCESS = "DONATE_LIST_SUCCESS";
export const DONATE_LIST_FAIL = "DONATE_LIST_FAIL";
export const DONATE_LIST_RESET = "DONATE_LIST_RESET";

export const DONATE_UPDATE_REQUEST = "DONATE_UPDATE_REQUEST";
export const DONATE_UPDATE_SUCCESS = "DONATE_UPDATE_SUCCESS";
export const DONATE_UPDATE_FAIL = "DONATE_UPDATE_FAIL";
export const DONATE_UPDATE_RESET = "DONATE_UPDATE_RESET";

export const DONATE_DELETE_REQUEST = "DONATE_DELETE_REQUEST";
export const DONATE_DELETE_SUCCESS = "DONATE_DELETE_SUCCESS";
export const DONATE_DELETE_FAIL = "DONATE_DELETE_FAIL";