export const ECARD_ORDER_CREATE_RESET = 'ECARD_ORDER_CREATE_RESET';

export const ECARD_ORDER_DETAILS_REQUEST = 'ECARD_ORDER_DETAILS_REQUEST';
export const ECARD_ORDER_DETAILS_SUCCESS = 'ECARD_ORDER_DETAILS_SUCCESS';
export const ECARD_ORDER_DETAILS_FAIL = 'ECARD_ORDER_DETAILS_FAIL';
