export const ECARD_ORDER_CREATE_REQUEST = 'ECARD_ORDER_CREATE_REQUEST';
export const ECARD_ORDER_CREATE_SUCCESS = 'ECARD_ORDER_CREATE_SUCCESS';
export const ECARD_ORDER_CREATE_FAIL = 'ECARD_ORDER_CREATE_FAIL';
export const ECARD_ORDER_CREATE_RESET = 'ECARD_ORDER_CREATE_RESET';

export const ECARD_ORDER_DETAILS_REQUEST = 'ECARD_ORDER_DETAILS_REQUEST';
export const ECARD_ORDER_DETAILS_SUCCESS = 'ECARD_ORDER_DETAILS_SUCCESS';
export const ECARD_ORDER_DETAILS_FAIL = 'ECARD_ORDER_DETAILS_FAIL';

export const ECARD_ORDERS_LIST_REQUEST = 'ECARD_ORDERS_LIST_REQUEST';
export const ECARD_ORDERS_LIST_SUCCESS = 'ECARD_ORDER_LIST_SUCCESS';
export const ECARD_ORDERS_LIST_FAIL = 'ECARD_ORDERS_LIST_FAIL';
