export const ECARD_LIST_REQUEST = 'ECARD_LIST_REQUEST';
export const ECARD_LIST_SUCCESS = 'ECARD_LIST_SUCCESS';
export const ECARD_LIST_FAIL = 'ECARD_LIST_FAIL';
export const ECARD_LIST_RESET = 'ECARD_LIST_RESET';

export const ECARD_CREATE_REQUEST = 'ECARD_CREATE_REQUEST';
export const ECARD_CREATE_SUCCESS = 'ECARD_CREATE_SUCCESS';
export const ECARD_CREATE_FAIL = 'ECARD_CREATE_FAIL';
export const ECARD_CREATE_RESET = 'ECARD_CREATE_RESET';

export const ECARD_DETAILS_REQUEST = 'ECARD_DETAILS_REQUEST';
export const ECARD_DETAILS_SUCCESS = 'ECARD_DETAILS_SUCCESS';
export const ECARD_DETAILS_FAIL = 'ECARD_DETAILS_FAIL';
export const ECARD_DETAILS_RESET = 'ECARD_DETAILS_RESET';

export const ECARD_UPDATE_REQUEST = 'ECARD_UPDATE_REQUEST';
export const ECARD_UPDATE_SUCCESS = 'ECARD_UPDATE_SUCCESS';
export const ECARD_UPDATE_FAIL = 'ECARD_UPDATE_FAIL';
export const ECARD_UPDATE_RESET = 'ECARD_UPDATE_RESET';

export const ECARD_DELETE_REQUEST = 'ECARD_DELETE_REQUEST';
export const ECARD_DELETE_SUCCESS = 'ECARD_DELETE_SUCCESS';
export const ECARD_DELETE_FAIL = 'ECARD_DELETE_FAIL';
