export const EDUCATION_TIP_LIST_REQUEST = 'EDUCATION_TIP_LIST_REQUEST';
export const EDUCATION_TIP_LIST_SUCCESS = 'EDUCATION_TIP_LIST_SUCCESS';
export const EDUCATION_TIP_LIST_FAIL = 'EDUCATION_TIP_LIST_FAIL';
export const EDUCATION_TIP_LIST_RESET = 'EDUCATION_TIP_LIST_RESET';

export const EDUCATION_TIP_CREATE_REQUEST = 'EDUCATION_TIP_CREATE_REQUEST';
export const EDUCATION_TIP_CREATE_SUCCESS = 'EDUCATION_TIP_CREATE_SUCCESS';
export const EDUCATION_TIP_CREATE_FAIL = 'EDUCATION_TIP_CREATE_FAIL';
export const EDUCATION_TIP_CREATE_RESET = 'EDUCATION_TIP_CREATE_RESET';

export const EDUCATION_TIP_DETAILS_REQUEST = 'EDUCATION_TIP_DETAILS_REQUEST';
export const EDUCATION_TIP_DETAILS_SUCCESS = 'EDUCATION_TIP_DETAILS_SUCCESS';
export const EDUCATION_TIP_DETAILS_FAIL = 'EDUCATION_TIP_DETAILS_FAIL';
export const EDUCATION_TIP_DETAILS_RESET = 'EDUCATION_TIP_DETAILS_RESET';

export const EDUCATION_TIP_UPDATE_REQUEST = 'EDUCATION_TIP_UPDATE_REQUEST';
export const EDUCATION_TIP_UPDATE_SUCCESS = 'EDUCATION_TIP_UPDATE_SUCCESS';
export const EDUCATION_TIP_UPDATE_FAIL = 'EDUCATION_TIP_UPDATE_FAIL';
export const EDUCATION_TIP_UPDATE_RESET = 'EDUCATION_TIP_UPDATE_RESET';

export const EDUCATION_TIP_DELETE_REQUEST = 'EDUCATION_TIP_DELETE_REQUEST';
export const EDUCATION_TIP_DELETE_SUCCESS = 'EDUCATION_TIP_DELETE_SUCCESS';
export const EDUCATION_TIP_DELETE_FAIL = 'EDUCATION_TIP_DELETE_FAIL';
