export const GUEST_USER_REGISTER_REQUEST = 'GUEST_USER_REGISTER_REQUEST';
export const GUEST_USER_REGISTER_SUCCESS = 'GUEST_USER_REGISTER_SUCCESS';
export const GUEST_USER_REGISTER_FAIL = 'GUEST_USER_REGISTER_FAIL';
export const GUEST_USER_REGISTER_RESET = 'GUEST_USER_REGISTER_RESET';
export const GUEST_USER_SUCCESS_RESET = 'GUEST_USER_SUCCESS_RESET';
