export const GUEST_ORDER_CREATE_REQUEST = 'GUEST_ORDER_CREATE_REQUEST';
export const GUEST_ORDER_CREATE_SUCCESS = 'GUEST_ORDER_CREATE_SUCCESS';
export const GUEST_ORDER_CREATE_FAIL = 'GUEST_ORDER_CREATE_FAIL';
export const GUEST_ORDER_CREATE_RESET = 'GUEST_ORDER_CREATE_RESET';

export const GUEST_ORDER_LIST_REQUEST = 'GUEST_ORDER_LIST_REQUEST';
export const GUEST_ORDER_LIST_SUCCESS = 'GUEST_ORDER_LIST_SUCCESS';
export const GUEST_ORDER_LIST_FAIL = 'GUEST_ORDER_LIST_FAIL';

export const GUEST_ORDER_SHIP_REQUEST = 'GUEST_ORDER_SHIP_REQUEST';
export const GUEST_ORDER_SHIP_SUCCESS = 'GUEST_ORDER_SHIP_SUCCESS';
export const GUEST_ORDER_SHIP_FAIL = 'GUEST_ORDER_SHIP_FAIL';
export const GUEST_ORDER_SHIP_RESET = 'GUEST_ORDER_SHIP_RESET';
