export const JWT_CHECK_VALIDITY_REQUEST = 'JWT_CHECK_VALIDITY_REQUEST';
export const JWT_CHECK_VALIDITY_SUCCESS = 'JWT_CHECK_VALIDITY_SUCCESS';
export const JWT_CHECK_VALIDITY_FAIL = 'JWT_CHECK_VALIDITY_FAIL';

export const JWT_CHECK_VALIDITY_ADOPTION_FEE_REQUEST =
  'JWT_CHECK_VALIDITY_ADOPTION_FEE_REQUEST';
export const JWT_CHECK_VALIDITY_ADOPTION_FEE_SUCCESS =
  'JWT_CHECK_VALIDITY_ADOPTION_FEE_SUCCESS';
export const JWT_CHECK_VALIDITY_ADOPTION_FEE_FAIL =
  'JWT_CHECK_VALIDITY_ADOPTION_FEE_FAIL';
export const JWT_CHECK_VALIDITY_ADOPTION_FEE_RESET =
  'JWT_CHECK_VALIDITY_ADOPTION_FEE_RESET';
