export const JWT_CHECK_VALIDITY_REQUEST = 'JWT_CHECK_VALIDITY_REQUEST';
export const JWT_CHECK_VALIDITY_SUCCESS = 'JWT_CHECK_VALIDITY_SUCCESS';
export const JWT_CHECK_VALIDITY_FAIL = 'JWT_CHECK_VALIDITY_FAIL';
