export const MANUALLY_ADD_USER_CREATE_REQUEST =
  'MANUALLY_ADD_USER_CREATE_REQUEST';
export const MANUALLY_ADD_USER_CREATE_SUCCESS =
  'MANUALLY_ADD_USER_CREATE_SUCCESS';
export const MANUALLY_ADD_USER_CREATE_FAIL = 'MANUALLY_ADD_USER_CREATE_FAIL';
export const MANUALLY_ADD_USER_CREATE_RESET = 'MANUALLY_ADD_USER_CREATE_RESET';

export const MANUALLY_ADD_USER_UPDATE_REQUEST =
  'MANUALLY_ADD_USER_UPDATE_REQUEST';
export const MANUALLY_ADD_USER_UPDATE_SUCCESS =
  'MANUALLY_ADD_USER_UPDATE_SUCCESS';
export const MANUALLY_ADD_USER_UPDATE_FAIL = 'MANUALLY_ADD_USER_UPDATE_FAIL';
export const MANUALLY_ADD_USER_UPDATE_RESET = 'MANUALLY_ADD_USER_UPDATE_RESET';

export const MANUALLY_ADD_USER_DELETE_REQUEST =
  'MANUALLY_ADD_USER_DELETE_REQUEST';
export const MANUALLY_ADD_USER_DELETE_SUCCESS =
  'MANUALLY_ADD_USER_DELETE_SUCCESS';
export const MANUALLY_ADD_USER_DELETE_FAIL = 'MANUALLY_ADD_USER_DELETE_FAIL';

export const MANUALLY_ADD_USER_LIST_REQUEST = 'MANUALLY_ADD_USER_LIST_REQUEST';
export const MANUALLY_ADD_USER_LIST_SUCCESS = 'MANUALLY_ADD_USER_LIST_SUCCESS';
export const MANUALLY_ADD_USER_LIST_FAIL = 'MANUALLY_ADD_USER_LIST_FAIL';

export const MANUALLY_ADD_USER_DETAILS_REQUEST =
  'MANUALLY_ADD_USER_DETAILS_REQUEST';
export const MANUALLY_ADD_USER_DETAILS_SUCCESS =
  'MANUALLY_ADD_USER_DETAILS_SUCCESS';
export const MANUALLY_ADD_USER_DETAILS_FAIL = 'MANUALLY_ADD_USER_DETAILS_FAIL';
