export const NEWSLETTER_EMAIL_CREATE_REQUEST =
  'NEWSLETTER_EMAIL_CREATE_REQUEST';
export const NEWSLETTER_EMAIL_CREATE_SUCCESS =
  'NEWSLETTER_EMAIL_CREATE_SUCCESS';
export const NEWSLETTER_EMAIL_CREATE_FAIL = 'NEWSLETTER_EMAIL_CREATE_FAIL';
export const NEWSLETTER_EMAIL_CREATE_RESET = 'NEWSLETTER_EMAIL_CREATE_RESET';

export const NEWSLETTER_EMAIL_LIST_REQUEST = 'NEWSLETTER_EMAIL_LIST_REQUEST';
export const NEWSLETTER_EMAIL_LIST_SUCCESS = 'NEWSLETTER_EMAIL_LIST_SUCCESS';
export const NEWSLETTER_EMAIL_LIST_FAIL = 'NEWSLETTER_EMAIL_LIST_FAIL';

export const NEWSLETTER_EMAIL_DELETE_REQUEST =
  'NEWSLETTER_EMAIL_DELETE_REQUEST';
export const NEWSLETTER_EMAIL_DELETE_SUCCESS =
  'NEWSLETTER_EMAIL_DELETE_SUCCESS';
export const NEWSLETTER_EMAIL_DELETE_FAIL = 'NEWSLETTER_EMAIL_DELETE_FAIL';
