export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';
export const ORDER_DETAILS_RESET = 'ORDER_DETAILS_RESET';

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST';
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS';
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL';
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET';

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL';

export const ORDER_SHIP_REQUEST = 'ORDER_SHIP_REQUEST';
export const ORDER_SHIP_SUCCESS = 'ORDER_SHIP_SUCCESS';
export const ORDER_SHIP_FAIL = 'ORDER_SHIP_FAIL';
export const ORDER_SHIP_RESET = 'ORDER_SHIP_RESET';

export const ORDER_EMAIL_CONFIRMATION_REQUEST =
  'ORDER_EMAIL_CONFIRMATION_REQUEST';
export const ORDER_EMAIL_CONFIRMATION_SUCCESS =
  'ORDER_EMAIL_CONFIRMATION_SUCCESS';
export const ORDER_EMAIL_CONFIRMATION_FAIL = 'ORDER_EMAIL_CONFIRMATION_FAIL';

export const TRACKING_NUMBER_REQUEST = 'TRACKING_NUMBER_REQUEST';
export const TRACKING_NUMBER_SUCCESS = 'TRACKING_NUMBER_SUCCESS';
export const TRACKING_NUMBER_FAIL = 'TRACKING_NUMBER_FAIL';
export const TRACKING_NUMBER_RESET = 'TRACKING_NUMBER_RESET';
