export const RAFFLE_WINNER_LIST_REQUEST = 'RAFFLE_WINNER_LIST_REQUEST';
export const RAFFLE_WINNER_LIST_SUCCESS = 'RAFFLE_WINNER_LIST_SUCCESS';
export const RAFFLE_WINNER_LIST_FAIL = 'RAFFLE_WINNER_LIST_FAIL';
export const RAFFLE_WINNER_LIST_RESET = 'RAFFLE_WINNER_LIST_RESET';

export const RAFFLE_WINNER_CREATE_REQUEST = 'RAFFLE_WINNER_CREATE_REQUEST';
export const RAFFLE_WINNER_CREATE_SUCCESS = 'RAFFLE_WINNER_CREATE_SUCCESS';
export const RAFFLE_WINNER_CREATE_FAIL = 'RAFFLE_WINNER_CREATE_FAIL';
export const RAFFLE_WINNER_CREATE_RESET = 'RAFFLE_WINNER_CREATE_RESET';

export const RAFFLE_WINNER_DETAILS_REQUEST = 'RAFFLE_WINNER_DETAILS_REQUEST';
export const RAFFLE_WINNER_DETAILS_SUCCESS = 'RAFFLE_WINNER_DETAILS_SUCCESS';
export const RAFFLE_WINNER_DETAILS_FAIL = 'RAFFLE_WINNER_DETAILS_FAIL';
export const RAFFLE_WINNER_DETAILS_RESET = 'RAFFLE_WINNER_DETAILS_RESET';

export const RAFFLE_WINNER_UPDATE_REQUEST = 'RAFFLE_WINNER_UPDATE_REQUEST';
export const RAFFLE_WINNER_UPDATE_SUCCESS = 'RAFFLE_WINNER_UPDATE_SUCCESS';
export const RAFFLE_WINNER_UPDATE_FAIL = 'RAFFLE_WINNER_UPDATE_FAIL';
export const RAFFLE_WINNER_UPDATE_RESET = 'RAFFLE_WINNER_UPDATE_RESET';

export const RAFFLE_WINNER_DELETE_REQUEST = 'RAFFLE_WINNER_DELETE_REQUEST';
export const RAFFLE_WINNER_DELETE_SUCCESS = 'RAFFLE_WINNER_DELETE_SUCCESS';
export const RAFFLE_WINNER_DELETE_FAIL = 'RAFFLE_WINNER_DELETE_FAIL';
