export const RESET_EMAIL_SEND_REQUEST = 'RESET_EMAIL_SEND_REQUEST';
export const RESET_EMAIL_SEND_SUCCESS = 'RESET_EMAIL_SEND_SUCCESS';
export const RESET_EMAIL_SEND_FAIL = 'RESET_EMAIL_SEND_FAIL';
export const RESET_EMAIL_SEND_RESET = 'RESET_EMAIL_SEND_RESET';

export const VERIFY_TOKEN_REQUEST = 'VERIFY_TOKEN_REQUEST';
export const VERIFY_TOKEN_SUCCESS = 'VERIFY_TOKEN_SUCCESS';
export const VERIFY_TOKEN_FAIL = 'VERIFY_TOKEN_FAIL';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
