export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET';

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';
export const USER_DETAILS_RESET = 'USER_DETAILS_RESET';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_WHO_WE_ARE_LIST_REQUEST = 'USER_WHO_WE_ARE_LIST_REQUEST';
export const USER_WHO_WE_ARE_LIST_SUCCESS = 'USER_WHO_WE_ARE_LIST_SUCCESS';
export const USER_WHO_WE_ARE_LIST_FAIL = 'USER_WHO_WE_ARE_LIST_FAIL';
export const USER_WHO_WE_ARE_LIST_RESET = 'USER_WHO_WE_ARE_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';
export const USER_DELETE_RESET = 'USER_DELETE_RESET';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';
export const USER_UPDATE_RESET = 'USER_UPDATE_RESET';

export const USER_LOGOUT_REQUEST = 'USER_LOGOUT_REQUEST';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAIL = 'USER_LOGOUT_FAIL';
export const USER_LOGOUT_RESET = 'USER_LOGOUT_RESET';

export const USER_OLD_PASSWORD_REQUEST = 'USER_OLD_PASSWORD_REQUEST';
export const USER_OLD_PASSWORD_SUCCESS = 'USER_OLD_PASSWORD_SUCCESS';
export const USER_OLD_PASSWORD_FAIL = 'USER_OLD_PASSWORD_FAIL';
export const USER_OLD_PASSWORD_RESET = 'USER_OLD_PASSWORD_RESET';

export const USER_VERIFY_EMAIL_REQUEST = 'USER_VERIFY_EMAIL_REQUEST';
export const USER_VERIFY_EMAIL_SUCCESS = 'USER_VERIFY_EMAIL_SUCCESS';
export const USER_VERIFY_EMAIL_FAIL = 'USER_VERIFY_EMAIL_FAIL';
export const USER_VERIFY_EMAIL_RESET = 'USER_VERIFY_EMAIL_RESET';

export const USER_CONFIRMED_REQUEST = 'USER_CONFIRMED_REQUEST';
export const USER_CONFIRMED_SUCCESS = 'USER_CONFIRMED_SUCCESS';
export const USER_CONFIRMED_FAIL = 'USER_CONFIRMED_FAIL';
export const USER_CONFIRMED_RESET = 'USER_CONFIRMED_RESET';

export const USER_GENERATE_NEW_TOKEN_REQUEST =
  'USER_GENERATE_NEW_TOKEN_REQUEST';
export const USER_GENERATE_NEW_TOKEN_SUCCESS =
  'USER_GENERATE_NEW_TOKEN_SUCCESS';
export const USER_GENERATE_NEW_TOKEN_FAIL = 'USER_GENERATE_NEW_TOKEN_FAIL';
export const USER_GENERATE_NEW_TOKEN_RESET = 'USER_GENERATE_NEW_TOKEN_RESET';

export const USER_CHECK_IF_CONFIRMED_RESET = 'USER_CHECK_IF_CONFIRMED_RESET';
