export const WELCOME_WIENER_PRODUCT_LIST_REQUEST =
  'WELCOME_WIENER_PRODUCT_LIST_REQUEST';
export const WELCOME_WIENER_PRODUCT_LIST_SUCCESS =
  'WELCOME_WIENER_PRODUCT_LIST_SUCCESS';
export const WELCOME_WIENER_PRODUCT_LIST_FAIL =
  'WELCOME_WIENER_PRODUCT_LIST_FAIL';
export const WELCOME_WIENER_PRODUCT_LIST_RESET =
  'WELCOME_WIENER_PRODUCT_LIST_RESET';

export const WELCOME_WIENER_PRODUCT_CREATE_REQUEST =
  'WELCOME_WIENER_PRODUCT_CREATE_REQUEST';
export const WELCOME_WIENER_PRODUCT_CREATE_SUCCESS =
  'WELCOME_WIENER_PRODUCT_CREATE_SUCCESS';
export const WELCOME_WIENER_PRODUCT_CREATE_FAIL =
  'WELCOME_WIENER_PRODUCT_CREATE_FAIL';
export const WELCOME_WIENER_PRODUCT_CREATE_RESET =
  'WELCOME_WIENER_PRODUCT_CREATE_RESET';

export const WELCOME_WIENER_PRODUCT_UPDATE_REQUEST =
  'WELCOME_WIENER_PRODUCT_UPDATE_REQUEST';
export const WELCOME_WIENER_PRODUCT_UPDATE_SUCCESS =
  'WELCOME_WIENER_PRODUCT_UPDATE_SUCCESS';
export const WELCOME_WIENER_PRODUCT_UPDATE_FAIL =
  'WELCOME_WIENER_PRODUCT_UPDATE_FAIL';
export const WELCOME_WIENER_PRODUCT_UPDATE_RESET =
  'WELCOME_WIENER_PRODUCT_UPDATE_RESET';

export const WELCOME_WIENER_PRODUCT_GET_BY_ID_REQUEST =
  'WELCOME_WIENER_PRODUCT_GET_BY_ID_REQUEST';
export const WELCOME_WIENER_PRODUCT_GET_BY_ID_SUCCESS =
  'WELCOME_WIENER_PRODUCT_GET_BY_ID_SUCCESS';
export const WELCOME_WIENER_PRODUCT_GET_BY_ID_FAIL =
  'WELCOME_WIENER_PRODUCT_GET_BY_ID_FAIL';
export const WELCOME_WIENER_PRODUCT_GET_BY_ID_RESET =
  'WELCOME_WIENER_PRODUCT_GET_BY_ID_RESET';

export const WELCOME_WIENER_PRODUCT_DELETE_REQUEST =
  'WELCOME_WIENER_PRODUCT_DELETE_REQUEST';
export const WELCOME_WIENER_PRODUCT_DELETE_SUCCESS =
  'WELCOME_WIENER_PRODUCT_DELETE_SUCCESS';
export const WELCOME_WIENER_PRODUCT_DELETE_FAIL =
  'WELCOME_WIENER_PRODUCT_DELETE_FAIL';
export const WELCOME_WIENER_PRODUCT_DELETE_RESET =
  'WELCOME_WIENER_PRODUCT_DELETE_RESET';

export const WELCOME_WIENER_PRODUCT_BASE = '/api/welcome-wiener-product';
