export const WELCOME_WIENER_ORDER_CREATE_REQUEST =
  'WELCOME_WIENER_ORDER_CREATE_REQUEST';
export const WELCOME_WIENER_ORDER_CREATE_SUCCESS =
  'WELCOME_WIENER_ORDER_CREATE_SUCCESS';
export const WELCOME_WIENER_ORDER_CREATE_FAIL =
  'WELCOME_WIENER_ORDER_CREATE_FAIL';
export const WELCOME_WIENER_ORDER_CREATE_RESET =
  'WELCOME_WIENER_ORDER_CREATE_RESET';

export const WELCOME_WIENER_ORDER_DETAILS_REQUEST =
  'WELCOME_WIENER_ORDER_DETAILS_REQUEST';
export const WELCOME_WIENER_ORDER_DETAILS_SUCCESS =
  'WELCOME_WIENER_ORDER_DETAILS_SUCCESS';
export const WELCOME_WIENER_ORDER_DETAILS_FAIL =
  'WELCOME_WIENER_ORDER_DETAILS_FAIL';
export const WELCOME_WIENER_ORDER_DETAILS_RESET =
  'WELCOME_WIENER_ORDER_DETAILS_RESET';

export const WELCOME_WIENER_ORDER_LIST_REQUEST =
  'WELCOME_WIENER_ORDER_LIST_REQUEST';
export const WELCOME_WIENER_ORDER_LIST_SUCCESS =
  'WELCOME_WIENER_ORDER_LIST_SUCCESS';
export const WELCOME_WIENER_ORDER_LIST_FAIL = 'WELCOME_WIENER_ORDER_LIST_FAIL';

export const WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_REQUEST =
  'WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_REQUEST';
export const WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_SUCCESS =
  'WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_SUCCESS';
export const WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_FAIL =
  'WELCOME_WIENER_ORDER_EMAIL_COMFIRMATION_FAIL';
