export const WELCOME_WIENER_DACHSHUND_LIST_REQUEST =
  'WELCOME_WIENER_DACHSHUND_LIST_REQUEST';
export const WELCOME_WIENER_DACHSHUND_LIST_SUCCESS =
  'WELCOME_WIENER_DACHSHUND_LIST_SUCCESS';
export const WELCOME_WIENER_DACHSHUND_LIST_FAIL =
  'WELCOME_WIENER_DACHSHUND_LIST_FAIL';
export const WELCOME_WIENER_DACHSHUND_LIST_RESET =
  'WELCOME_WIENER_DACHSHUND_LIST_RESET';

export const WELCOME_WIENER_DACHSHUND_CREATE_REQUEST =
  'WELCOME_WIENER_DACHSHUND_CREATE_REQUEST';
export const WELCOME_WIENER_DACHSHUND_CREATE_SUCCESS =
  'WELCOME_WIENER_DACHSHUND_CREATE_SUCCESS';
export const WELCOME_WIENER_DACHSHUND_CREATE_FAIL =
  'WELCOME_WIENER_DACHSHUND_CREATE_FAIL';
export const WELCOME_WIENER_DACHSHUND_CREATE_RESET =
  'WELCOME_WIENER_DACHSHUND_CREATE_RESET';

export const WELCOME_WIENER_DACHSHUND_UPDATE_REQUEST =
  'WELCOME_WIENER_DACHSHUND_UPDATE_REQUEST';
export const WELCOME_WIENER_DACHSHUND_UPDATE_SUCCESS =
  'WELCOME_WIENER_DACHSHUND_UPDATE_SUCCESS';
export const WELCOME_WIENER_DACHSHUND_UPDATE_FAIL =
  'WELCOME_WIENER_DACHSHUND_UPDATE_FAIL';
export const WELCOME_WIENER_DACHSHUND_UPDATE_RESET =
  'WELCOME_WIENER_DACHSHUND_UPDATE_RESET';

export const WELCOME_WIENER_DACHSHUND_GET_BY_ID_REQUEST =
  'WELCOME_WIENER_DACHSHUND_GET_BY_ID_REQUEST';
export const WELCOME_WIENER_DACHSHUND_GET_BY_ID_SUCCESS =
  'WELCOME_WIENER_DACHSHUND_GET_BY_ID_SUCCESS';
export const WELCOME_WIENER_DACHSHUND_GET_BY_ID_FAIL =
  'WELCOME_WIENER_DACHSHUND_GET_BY_ID_FAIL';

export const WELCOME_WIENER_DACHSHUND_DELETE_REQUEST =
  'WELCOME_WIENER_DACHSHUND_DELETE_REQUEST';
export const WELCOME_WIENER_DACHSHUND_DELETE_SUCCESS =
  'WELCOME_WIENER_DACHSHUND_DELETE_SUCCESS';
export const WELCOME_WIENER_DACHSHUND_DELETE_FAIL =
  'WELCOME_WIENER_DACHSHUND_DELETE_FAIL';

export const WELCOME_WIENER_DACHSHUND_BASE = '/api/welcome-wiener-dog';

export const TOGGLE_WELCOME_DACHSHUND_REQUEST =
  'TOGGLE_WELCOME_DACHSHUND_REQUEST';
export const TOGGLE_WELCOME_DACHSHUND_SUCCESS =
  'TOGGLE_WELCOME_DACHSHUND_SUCCESS';
export const TOGGLE_WELCOME_DACHSHUND_FAIL = 'TOGGLE_WELCOME_DACHSHUND_FAIL';
export const TOGGLE_WELCOME_DACHSHUND_RESET = 'TOGGLE_WELCOME_DACHSHUND_RESET';
