export const eCardCategories = [
  'Anniversary',
  'Baby Shower',
  'Birthday',
  'Best Wishes',
  'Bon Voyage',
  'Christmas',
  'Congratulations',
  'Easter',
  'Engagement',
  `Father's Day`,
  'Farewell',
  'Get Well Soon',
  'Good Luck',
  'Graduation',
  'Halloween',
  'Holiday',
  'Independence Day',
  'July 4th',
  'Juneteenth',
  'Memorial Day',
  `Mother's Day`,
  `New Year's Day`,
  'Spring',
  `St. Patrick's Day`,
  'Sympathy',
  'Thanksgiving',
  'Thinking Of You',
  `Valentine's Day`,
  'Wedding',
];
